import bslint.constants as const
from bslint.parser.reduction_rule_handler import ReductionRuleHandler

rules = [
    ReductionRuleHandler([const.ID, const.OPERATOR, const.ID], [const.VALUE]),
    ReductionRuleHandler([const.VALUE, const.OPERATOR, const.VALUE], [const.VALUE]),
    ReductionRuleHandler([const.VALUE, const.OPERATOR, const.ID], [const.VALUE]),
    ReductionRuleHandler([const.ID, const.OPERATOR, const.VALUE], [const.VALUE]),
    ReductionRuleHandler([const.ID, const.OPERATOR, const.FUNCTION_CALL], [const.VALUE]),
    ReductionRuleHandler([const.FUNCTION_CALL, const.OPERATOR, const.ID], [const.VALUE]),
    ReductionRuleHandler([const.VALUE, const.OPERATOR, const.FUNCTION_CALL], [const.VALUE]),
    ReductionRuleHandler([const.FUNCTION_CALL, const.OPERATOR, const.VALUE], [const.VALUE]),
    ReductionRuleHandler([const.FUNCTION_CALL, const.OPERATOR, const.FUNCTION_CALL], [const.VALUE]),

    ReductionRuleHandler([const.ARGUMENT, const.COMMA, const.ARGUMENT, const.CLOSE_PARENTHESIS],
                         [const.ARGUMENT, const.CLOSE_PARENTHESIS]),
    ReductionRuleHandler([const.ID, const.COMMA, const.ID, const.CLOSE_PARENTHESIS],
                         [const.ARGUMENT, const.CLOSE_PARENTHESIS]),
    ReductionRuleHandler([const.ID, const.COMMA, const.VALUE, const.CLOSE_PARENTHESIS],
                         [const.ARGUMENT, const.CLOSE_PARENTHESIS]),
    ReductionRuleHandler([const.ID, const.COMMA, const.ARGUMENT, const.CLOSE_PARENTHESIS],
                         [const.ARGUMENT, const.CLOSE_PARENTHESIS]),
    ReductionRuleHandler([const.VALUE, const.COMMA, const.ARGUMENT, const.CLOSE_PARENTHESIS],
                         [const.ARGUMENT, const.CLOSE_PARENTHESIS]),
    ReductionRuleHandler([const.VALUE, const.COMMA, const.ID, const.CLOSE_PARENTHESIS],
                         [const.ARGUMENT, const.CLOSE_PARENTHESIS]),
    ReductionRuleHandler([const.VALUE, const.COMMA, const.VALUE, const.CLOSE_PARENTHESIS],
                         [const.ARGUMENT, const.CLOSE_PARENTHESIS]),

    ReductionRuleHandler([const.FUNCTION, const.ID, const.OPEN_PARENTHESIS, const.CLOSE_PARENTHESIS],
                         [const.FUNCTION_DECLARATION]),
    ReductionRuleHandler([const.FUNCTION, const.ID, const.OPEN_PARENTHESIS, const.PARAM, const.CLOSE_PARENTHESIS],
                         [const.FUNCTION_DECLARATION]),
    ReductionRuleHandler([const.FUNCTION, const.ID, const.OPEN_PARENTHESIS, const.ID, const.CLOSE_PARENTHESIS],
                             [const.FUNCTION_DECLARATION]),
    ReductionRuleHandler([const.FUNCTION, const.ID, const.OPEN_PARENTHESIS, const.ARGUMENT, const.CLOSE_PARENTHESIS],
                             [const.FUNCTION_DECLARATION]),
    ReductionRuleHandler([const.SUB, const.ID, const.OPEN_PARENTHESIS, const.CLOSE_PARENTHESIS],
                         [const.FUNCTION_DECLARATION]),
    ReductionRuleHandler([const.SUB, const.ID, const.OPEN_PARENTHESIS, const.PARAM, const.CLOSE_PARENTHESIS],
                         [const.FUNCTION_DECLARATION]),
    ReductionRuleHandler([const.SUB, const.ID, const.OPEN_PARENTHESIS, const.ID, const.CLOSE_PARENTHESIS],
                             [const.FUNCTION_DECLARATION]),
    ReductionRuleHandler([const.SUB, const.ID, const.OPEN_PARENTHESIS, const.ARGUMENT, const.CLOSE_PARENTHESIS],
                             [const.FUNCTION_DECLARATION]),

    ReductionRuleHandler([const.ID, const.OPEN_PARENTHESIS, const.CLOSE_PARENTHESIS], [const.FUNCTION_CALL]),
    ReductionRuleHandler([const.ID, const.OPEN_PARENTHESIS, const.ARGUMENT, const.CLOSE_PARENTHESIS],
                         [const.FUNCTION_CALL]),
    ReductionRuleHandler([const.ID, const.OPEN_PARENTHESIS, const.VALUE, const.CLOSE_PARENTHESIS],
                         [const.FUNCTION_CALL]),
    ReductionRuleHandler([const.ID, const.OPEN_PARENTHESIS, const.ID, const.CLOSE_PARENTHESIS], [const.FUNCTION_CALL]),
    ReductionRuleHandler([const.ID, const.OPEN_PARENTHESIS, const.VAR_AS, const.CLOSE_PARENTHESIS],
                         [const.FUNCTION_CALL]),
    ReductionRuleHandler([const.ID, const.OPEN_PARENTHESIS, const.FUNCTION_CALL, const.CLOSE_PARENTHESIS],
                         [const.FUNCTION_CALL]),

    ReductionRuleHandler([const.OPEN_PARENTHESIS, const.VALUE, const.CLOSE_PARENTHESIS], [const.VALUE]),
    ReductionRuleHandler([const.OPEN_PARENTHESIS, const.ID, const.CLOSE_PARENTHESIS], [const.VALUE]),
    ReductionRuleHandler([const.OPEN_PARENTHESIS, const.VAR_AS, const.CLOSE_PARENTHESIS], [const.VALUE]),

    ReductionRuleHandler([const.ID, const.EQUALS, const.ID], [const.VAR_AS]),
    ReductionRuleHandler([const.ID, const.EQUALS, const.VALUE], [const.VAR_AS]),
    ReductionRuleHandler([const.ID, const.EQUALS, const.FUNCTION_CALL], [const.VAR_AS]),

    ReductionRuleHandler([const.PARAM, const.COMMA, const.PARAM], [const.PARAM]),
    ReductionRuleHandler([const.ID, const.AS, const.TYPE], [const.PARAM]),
    ReductionRuleHandler([const.VAR_AS, const.AS, const.TYPE], [const.PARAM]),

    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.VALUE], [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.VALUE, const.STEP, const.VALUE],
                         [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.VALUE, const.STEP, const.ID],
                         [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.VALUE, const.STEP, const.FUNCTION_CALL],
                         [const.FOR_STATEMENT]),

    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.ID], [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.ID, const.STEP, const.VALUE],
                         [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.ID, const.STEP, const.ID],
                         [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.ID, const.STEP, const.FUNCTION_CALL],
                         [const.FOR_STATEMENT]),

    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.FUNCTION_CALL], [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.FUNCTION_CALL, const.STEP, const.VALUE],
                         [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.FUNCTION_CALL, const.STEP, const.ID],
                         [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.FOR, const.VAR_AS, const.TO, const.FUNCTION_CALL, const.STEP, const.FUNCTION_CALL],
                         [const.FOR_STATEMENT]),
    ReductionRuleHandler([const.WHILE, const.VAR_AS], [const.WHILE_STATEMENT]),
    ReductionRuleHandler([const.WHILE, const.ID], [const.WHILE_STATEMENT]),
    ReductionRuleHandler([const.WHILE, const.VALUE], [const.WHILE_STATEMENT]),
    ReductionRuleHandler([const.WHILE, const.FUNCTION_CALL], [const.WHILE_STATEMENT]),

    ReductionRuleHandler([const.END_FOR_TOKEN], [const.END_FOR]),
    ReductionRuleHandler([const.END_IF_TOKEN], [const.END_IF]),
    ReductionRuleHandler([const.END_WHILE_TOKEN], [const.END_WHILE]),
    ReductionRuleHandler([const.END_SUB_TOKEN], [const.END_SUB]),
    ReductionRuleHandler([const.END_FUNCTION_TOKEN], [const.END_FUNCTION]),
    ReductionRuleHandler([const.END_TOKEN], [const.END]),
]
