# this characters need escaping . ^ $ * + ? { } [ ] \ | ( )
import Constants as const

List = [
    (r"\n", const.NEW_LINE),
    (r"\s", None),


    ("\+=", const.OPERATOR),
    ("-=", const.OPERATOR),
    ("\*=", const.OPERATOR),
    ("/=", const.OPERATOR),
    (r"\\=", const.OPERATOR),  # divide integer
    ("<<=", const.OPERATOR),
    (">>=", const.OPERATOR),
    ("<>", const.OPERATOR),
    (">=", const.OPERATOR),
    ("<=", const.OPERATOR),
    (">=", const.OPERATOR),
    ("=>", const.OPERATOR),
    ("=<", const.OPERATOR),

    (">>", const.OPERATOR),
    ("<<", const.OPERATOR),

    (r"\.", const.OPERATOR),
    (r"\^", const.OPERATOR),
    ("=", const.OPERATOR),
    ("-", const.OPERATOR),
    ("\+", const.OPERATOR),
    ("\*", const.OPERATOR),
    (r"/", const.OPERATOR),
    ("<", const.OPERATOR),
    (">", const.OPERATOR),

    (r"\(", const.BRACKET),
    (r"\)", const.BRACKET),
    (r"\[", const.SQUARE_BRACKET),
    (r"\]", const.SQUARE_BRACKET),

    ("TRUE", const.KEYWORD),
    ("GETLASTRUNCOMPILEERROR", const.KEYWORD),
    ("GETLASTRUNRUNTIMEERROR", const.KEYWORD),
    ("GETGLOBALAA", const.KEYWORD),
    ("ELSE IF", const.KEYWORD),
    ("END IF", const.KEYWORD),
    ("EXIT FOR", const.KEYWORD),
    ("FOR EACH", const.KEYWORD),
    ("END FOR", const.KEYWORD),
    ("END WHILE", const.KEYWORD),
    ("EXIT WHILE", const.KEYWORD),
    ("END FUNCTION", const.KEYWORD),
    ("END SUB", const.KEYWORD),
    ("LINE_NUM", const.KEYWORD),
    ("GOTO", const.KEYWORD),
    ("CREATEOBJECT", const.KEYWORD),
    ("ELSEIF", const.KEYWORD),
    ("ENDIF", const.KEYWORD),
    ("ENDWHILE", const.KEYWORD),
    ("EXITWHILE", const.KEYWORD),
    ("ENDFUNCTION", const.KEYWORD),
    ("ENDSUB", const.KEYWORD),
    ("OBJFUN", const.KEYWORD),

    ("IF", const.KEYWORD),
    ("THEN", const.KEYWORD),
    ("ELSE", const.KEYWORD),
    ("FOR", const.KEYWORD),
    ("TO", const.KEYWORD),
    ("STEP", const.KEYWORD),
    ("INVALID", const.KEYWORD),
    ("IN", const.KEYWORD),
    ("WHILE", const.KEYWORD),
    ("FUNCTION", const.KEYWORD),
    ("AS", const.KEYWORD),
    ("RETURN", const.KEYWORD),
    ("PRINT", const.KEYWORD),
    ("DIM", const.KEYWORD),
    ("END", const.KEYWORD),
    ("MOD", const.KEYWORD),
    ("STOP", const.KEYWORD),
    ("AND", const.KEYWORD),
    ("BOX", const.KEYWORD),
    ("EACH", const.KEYWORD),
    ("EVAL", const.KEYWORD),
    ("EXIT", const.KEYWORD),
    ("FALSE", const.KEYWORD),
    ("LET", const.KEYWORD),
    ("NEXT", const.KEYWORD),
    ("NOT", const.KEYWORD),
    ("OR", const.KEYWORD),
    ("POS", const.KEYWORD),
    (r"('|rem)\s*(BSLINT)_(?P<command>[a-z_]+)(:(?P<param>[0-9]+))?.*\n", const.BSLINT_COMMAND),
    ("('|REM)(.*)\n", None),
    ("RUN", const.KEYWORD),
    ("SUB", const.KEYWORD),
    ("TAB", const.KEYWORD),
    ("TYPE", const.KEYWORD),



    ("MAIN", const.KEYWORD),
    ("\?", const.KEYWORD),

    (r"(?P<value>^[a-z_][a-z0-9_]*)(?P<type>\$|%|!|#|&?)", const.ID),
    ('\"(.*)\"', const.STRING),
    (r"^\d*(\.?\d+){1}", const.NUMERIC)
]
