# this characters need escaping . ^ $ * + ? { } [ ] \ | ( )
import Constants as const

List = [
    (r"\n", const.NEW_LINE),
    (r"\s", None),


    ("\+=", const.OPERATOR),
    ("-=", const.OPERATOR),
    ("\*=", const.OPERATOR),
    ("/=", const.OPERATOR),
    (r"\\=", const.OPERATOR),  # divide integer
    ("<<=", const.OPERATOR),
    (">>=", const.OPERATOR),
    ("<>", const.OPERATOR),
    (">=", const.OPERATOR),
    ("<=", const.OPERATOR),
    (">=", const.OPERATOR),
    ("=>", const.OPERATOR),
    ("=<", const.OPERATOR),

    (">>", const.OPERATOR),
    ("<<", const.OPERATOR),

    (r"\.", const.OPERATOR),
    (r"\^", const.OPERATOR),
    ("=", const.OPERATOR),
    ("-", const.OPERATOR),
    ("\+", const.OPERATOR),
    ("\*", const.OPERATOR),
    (r"/", const.OPERATOR),
    ("<", const.OPERATOR),
    (">", const.OPERATOR),

    (r"\(", const.BRACKET),
    (r"\)", const.BRACKET),
    (r"\[", const.SQUARE_BRACKET),
    (r"\]", const.SQUARE_BRACKET),

    ("TRUE(?:\t*)", const.KEYWORD),
    ("GETLASTRUNCOMPILEERROR(?:\t*)", const.KEYWORD),
    ("GETLASTRUNRUNTIMEERROR(?:\t*)", const.KEYWORD),
    ("GETGLOBALAA(?:\t*)", const.KEYWORD),
    ("ELSE IF(?:\t*)", const.KEYWORD),
    ("END IF(?:\t*)", const.KEYWORD),
    ("EXIT FOR(?:\t*)", const.KEYWORD),
    ("FOR EACH(?:\t*)", const.KEYWORD),
    ("END FOR(?:\t*)", const.KEYWORD),
    ("END WHILE(?:\t*)", const.KEYWORD),
    ("EXIT WHILE(?:\t*)", const.KEYWORD),
    ("END FUNCTION(?:\t*)", const.KEYWORD),
    ("END SUB(?:\t*)", const.KEYWORD),
    ("LINE_NUM(?:\t*)", const.KEYWORD),
    ("GOTO(?:\t*)", const.KEYWORD),
    ("CREATEOBJECT(?:\t*)", const.KEYWORD),
    ("ELSEIF(?:\t*)", const.KEYWORD),
    ("ENDIF(?:\t*)", const.KEYWORD),
    ("ENDWHILE(?:\t*)", const.KEYWORD),
    ("EXITWHILE(?:\t*)", const.KEYWORD),
    ("ENDFUNCTION(?:\t*)", const.KEYWORD),
    ("ENDSUB(?:\t*)", const.KEYWORD),
    ("OBJFUN(?:\t*)", const.KEYWORD),

    ("IF(?:\t*)", const.KEYWORD),
    ("THEN(?:\t*)", const.KEYWORD),
    ("ELSE(?:\t*)", const.KEYWORD),
    ("FOR(?:\t*)", const.KEYWORD),
    ("TO(?:\t*)", const.KEYWORD),
    ("STEP(?:\t*)", const.KEYWORD),
    ("INVALID(?:\t*)", const.KEYWORD),
    ("IN(?:\t*)", const.KEYWORD),
    ("WHILE(?:\t*)", const.KEYWORD),
    ("FUNCTION(?:\t*)", const.KEYWORD),
    ("AS(?:\t*)", const.KEYWORD),
    ("RETURN(?:\t*)", const.KEYWORD),
    ("PRINT(?:\t*)", const.KEYWORD),
    ("DIM(?:\t*)", const.KEYWORD),
    ("END(?:\t*)", const.KEYWORD),
    ("MOD(?:\t*)", const.KEYWORD),
    ("STOP(?:\t*)", const.KEYWORD),
    ("(AND)(?:\t*)", const.KEYWORD),
    ("BOX(?:\t*)", const.KEYWORD),
    ("EACH(?:\t*)", const.KEYWORD),
    ("EVAL(?:\t*)", const.KEYWORD),
    ("EXIT(?:\t*)", const.KEYWORD),
    ("FALSE(?:\t*)", const.KEYWORD),
    ("LET(?:\t*)", const.KEYWORD),
    ("NEXT(?:\t*)", const.KEYWORD),
    ("NOT(?:\t*)", const.KEYWORD),
    ("OR(?:\t*)", const.KEYWORD),
    ("POS(?:\t*)", const.KEYWORD),
    (r"('|rem)\s*(BSLINT)_(?P<command>[a-z_]+)(:(?P<param>[0-9]+))?.*", const.BSLINT_COMMAND),
    ("('|REM)(.*)", const.COMMENT),
    ("RUN(?:\t*)", const.KEYWORD),
    ("SUB(?:\t*)", const.KEYWORD),
    ("TAB(?:\t*)", const.KEYWORD),
    ("TYPE(?:\t*)", const.KEYWORD),



    ("MAIN(?:\t*)", const.KEYWORD),
    ("\?", const.KEYWORD),

    (r"(?P<value>^[a-z_][a-z0-9_]*)(?P<type>\$|%|!|#|&?)", const.ID),
    ('\"(.*)\"', const.STRING),
    (r"^\d*(\.?\d+){1}", const.NUMERIC)
]
